### PR TITLE
enable NetCDF

### LINKED ISSUE #120: Possible to build with NETCDF package included
### Comment:

Would it be as simple as adding `-DPKG_NETCDF=ON` to `args` in `recipe/build.sh` and adding `netcdf4` as a host requirement in `recipe/meta.yaml`? If so, I can open a PR...

### PR DESCRIPTION
**Pull request by jimustafa**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Attempts to close #120.

### CODE REVIEW

**Comment by jimustafa** [comment]
How to ensure that the license file is being packaged?

**Comment by jimustafa** [comment]
Attempts to close #121.

**Comment by jan-janssen** [comment]
> How to ensure that the license file is being packaged?

It is packaged by default as it is linked in the `meta.yaml` file, otherwise the conda-forge bot complains.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Pull request merged**
