### PR TITLE
MPI Matrix

### PR DESCRIPTION
**Pull request by dougalsutherland**
This is I think the conda-smithy 3 way to do MPI variants. I'm not totally sure this is right, though....

* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
@conda-forge/core, is it okay if the build string has a space in it? Is this the right way to do MPI variants now?

cc @conda-forge/mpi @conda-forge/mpi4py

**Comment by dougalsutherland** [comment]
Apparently it is not okay for the build string to have a space in it.

Will try another thing later, but this could maybe be considered a `conda-smithy` bug.

**Comment by msarahan** [comment]
Ah, that's interesting.  There needs to be a 2-step templating thing here.  Think something like this:

```
mpi:
  - openmpi
  - mpich
openmpi:
  - 3.0
mpich:
  - 3.2
```

and in meta.yaml, you *might* need to be explicit about which variable you want:

```
  - {{ mpi }} {{ openmpi if mpi == 'openmpi' else mpich}}
```

or maybe:

```
  - {{ mpi }} {{ openmpi }}   # [mpi == 'openmpi']
  - {{ mpi }} {{ mpich }}   # [mpi == 'mpich']
```

Both of these are pretty hideous.  With only mpi to complain about here, I'm inclined to recommend adding a new jinja2 function that will roll this stuff up into a single function call, like:

```
  - {{ mpi() }}
```

and that function could take care of looping over all mpi implementations, as well as any multiple versions desired within each implementation.  The rules would be something like:

1. entries under the mpi key are package names only
2. keys matching entries are interpreted as lists of version pins for those entries.
3. any entry without a missing key is assumed to not have a version pin.

**Comment by msarahan** [comment]
PS: I may also be completely off base, and we just need a hack here.  However, keep in mind that the output filename must be valid, and characters like >, <, * and such may cause unexpected side effects.  We may need a sanitize step for the filename generation.

**Comment by dougalsutherland** [comment]
I tried doing something like the second one and got a crash, but didn’t have time to debug further. Will look into it.

If we pin openmpi and mpich, with appropriate pin_run_as_build or run_exports, it’d be relatively easy. Should probably just do that right?

**Comment by msarahan** [comment]
not quite.  It would work to set bounds for the run env, but you still need something like you have expressed right now in order to set the version that should be present in the build env.

**Comment by dougalsutherland** [comment]
What I meant was something like how we handle numpy:

In `conda-forge-pinning`:
```
mpich:
  - 3.2
openmpi:
  - 3.0
pin_run_as_build:  # or not if there's run_exports
  mipich:
    max_pin: x.x
  openmpi:
    max_pin: x.x
```

`conda_build_config.yaml`:
```
mpi:
  - openmpi
  - mpich
```

`meta.yaml`:
```
requirements:
  host:
    - {{ mpi }}
  run:
    - {{ pin_compatible(mpi) }}  # or nothing if there's run_exports
```

Would that not work for some reason?

**Comment by msarahan** [comment]
It might work.  The only reason it might not is that I'm not completely certain that conda-build will do the name matching for package names that are dynamically defined as template variables.

pin_compatible and pin_run_as_build do the same thing in different ways, so you should choose one.  pin_compatible affects only one recipe, pin_run_as_build affects all recipes that you use that config with.

with pin_run_as_build:

```
host:
  - {{ mpi }}
run:
  - {{ mpi }}
```

*might* work.  The key things to keep in mind are "what is the state of the recipe at the time that I expect this operation to happen?" and "What state is conda-build using to build on/substitute into?"

Many/most, maybe even all times the answer to the latter is "the raw template" and what is changing is the collection of variables provided to that template.

**Comment by dougalsutherland** [comment]
Just using `- {{ mpi }}` doesn't seem to pull in a version constraint.

Something like `- {{ mpi }} {{ locals()[mpi] }}` could work, except that we don't have `locals()` available in the jinja env. I poked a bit through conda-build source and didn't see anything that would work as an equivalent, either.

It seems like the best option for now is something like:

```
    - openmpi {{ openmpi }}  # [mpi == "openmpi"]
    - mpich   {{ mpich }}    # [mpi == "mpich"]
```
You could change the first bit to `{{ mpi }}` if you wanted, but that doesn't seem to really do anything.

**Comment by dougalsutherland** [comment]
(Not a terrible idea, makes the recipe a little nicer at least. But probably need `{{ mpi }} {{ mpi_impl_version }}` in `run` too, right? Or else add `pin_run_as_build` or `run_exports`; `mpich` / `openmpi` have neither currently.)

Is there a fundamental reason why we expect the MPI tests to fail on the CI? `mpich` gives
```+ mpiexec -n 1 lmp_mpi -help
Fatal error in PMPI_Comm_rank: Invalid communicator, error stack:
PMPI_Comm_rank(110): MPI_Comm_rank(comm=0x0, rank=0x626a459c) failed
PMPI_Comm_rank(68).: Invalid communicator```
and `openmpi` gives
```+ mpiexec -n 1 lmp_mpi -help
--------------------------------------------------------------------------
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
--------------------------------------------------------------------------
[5897057d4f9b:08416] [[INVALID],INVALID] FORCE-TERMINATE AT Not found:-13 - error plm_rsh_component.c(327)
[5897057d4f9b:08416] *** Process received signal ***
[5897057d4f9b:08416] Signal: Segmentation fault (11)
[5897057d4f9b:08416] Signal code: Address not mapped (1)
[5897057d4f9b:08416] Failing at address: (nil)
[5897057d4f9b:08416] [ 0] /lib64/libpthread.so.0(+0xf7e0)[0x7fdcbcbcf7e0]
[5897057d4f9b:08416] *** End of error message ***
/home/conda/feedstock_root/build_artifacts/lammps_1527099672155/test_tmp/run_test.sh: line 8:  8416 Segmentation fault      (core dumped) mpiexec -n 1 lmp_mpi -help > help_mpi.txt```
That command works for me locally with the current build, without having done any special configuration, though.

**Comment by minrk** [comment]
I thought part of the idea of things like pin_run_as_build is that we don't need to specify the build version dependency, only `pin_run_as_build`?

```yaml
# conda_build_config.yaml
mpi:
  - mpich
  - openmpi

pin_run_as_build:
  mpich: x.x
  openmpi: x.x
```

```yaml
# meta.yaml
requirements:
  host:
    - {{ mpi }}
  run:
    - {{ mpi }}
```

Then if conda-forge-pinning specifies that mpich should be pinned to 3.1.x that would be applied in the build environment, and then pin_run_as_build would do the right thing, right?

**Comment by minrk** [comment]
BTW, I've started adding run_exports to mpich and openmpi, so the pin_run_as_build should stop being necessary shortly:

- https://github.com/conda-forge/mpich-feedstock/pull/20
- https://github.com/conda-forge/openmpi-feedstock/pull/21

At which point, I think the right thing to do is what @dougalsutherland pointed to above:

```yaml
# conda-forge-pinning
mpich:
  - 3.2
openmpi:
  - 3.1

# conda_build_config.yaml:
mpi:
  - openmpi
  - mpich

# meta.yaml:
requirements:
  host:
    - {{ mpi }}
```

**Comment by minrk** [comment]
As for the failures with openmpi, I believe you need to set some environment variables for it to run on the CI setups:

```bash
export OMPI_MCA_plm=isolated
export OMPI_MCA_btl_vader_single_copy_mechanism=none
export OMPI_MCA_rmaps_base_oversubscribe=yes
```

[ref](https://github.com/conda-forge/openmpi-feedstock/blob/433c4187944f347773aa7361ee58d820a74cec6b/recipe/run_test.sh#L22-L24). I haven't seen the mpich issue before.

**Comment by dalcinl** [comment]
@dougalsutherland The error you get with MPICH is very unlikely a problem with MPICH itself. My bet is that somehow the binary was built or linked (either at compile time or dynamically at runtime) with the Open MPI header or library, that's the reason you see `comm=0x0` in the error message. In MPICH, it is almost impossible that a correct program will endup with `comm=0x0`, even `MPI_COMM_NULL` is defined as `0x04000000`. Either the program EXPLICITY assigns `comm=0x0` (would be very bad API usage, unless the coder REALLY know what she is doing), or that value comes from a different header. Or maybe you are running Fortran? In that case, what I said does not apply, comm handles are integers, very easy to get a bad assignment to zero.

**Comment by jan-janssen** [comment]
This is now implemented in 
https://github.com/conda-forge/lammps-feedstock/pull/4

**Pull request closed without merging**
