### PR TITLE
merge parallel and library builds; bump to stable_23Jun2022_update2

### LINKED ISSUE #123: enable shared library for lmp_mpi
### Comment:

When I use `lmp_mpi` from conda-forge to load my plugin

```lammps
plugin load libdeepmd_lmp.so
```
I got the following error:
```
undefined symbol: _ZTIN9LAMMPS_NS7ComputeE
````

Luckily, I am familiar with LAMMPS, so I realize that `liblammps.so` is not linked to LAMMPS, so I try
```
plugin load liblammps.so
plugin load libdeepmd_lmp.so
```
It does work.

I wonder if we can enable `BUILD_SHARED_LIBS=ON` for `lmp_mpi`, so the plugins can be loaded successfully without manually loading `liblammps.so` and we don't need to build again shared libraries.

### PR DESCRIPTION
**Pull request by njzjz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #123.

### CODE REVIEW

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by jan-janssen** [comment]
Can we separate these two steps? Having one pull request for the dump to 23June2022 and another one for the library builds?

**Comment by njzjz** [comment]
> Can we separate these two steps? Having one pull request for the dump to 23June2022 and another one for the library builds? 

It does make sense.

**Pull request closed without merging**
