### PR TITLE
build against MPI packages; add nompi build

### LINKED ISSUE #171: nompi dependencies are installed by default
### Comment:

When I install LAMMPS, I notice there are several `nompi` dependencies installed. Should MPI packages be expected to be installed?

See https://conda-forge.org/docs/maintainer/knowledge_base.html#complete-example

```
mamba create -n test2222 lammps -c conda-forge

Looking for: ['lammps']

conda-forge/noarch                                  12.8MB @  57.6MB/s  0.3s
conda-forge/linux-64                                31.0MB @  42.0MB/s  0.8s
Transaction

  Prefix: /home/jz748/anaconda3/envs/test2222

  Updating specs:

   - lammps


  Package                    Version  Build                         Channel           Size
────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                0.1  conda_forge                   conda-forge     Cached
  + libstdcxx-ng              13.2.0  h7e041cc_3                    conda-forge     Cached
  + python_abi                  3.11  4_cp311                       conda-forge     Cached
  + mpi                          1.0  openmpi                       conda-forge     Cached
  + ld_impl_linux-64            2.40  h41732ed_0                    conda-forge     Cached
  + ca-certificates       2023.11.17  hbcca054_0                    conda-forge     Cached
  + libgomp                   13.2.0  h807b86a_3                    conda-forge     Cached
  + _openmp_mutex                4.5  2_gnu                         conda-forge     Cached
  + libgcc-ng                 13.2.0  h807b86a_3                    conda-forge     Cached
  + xorg-libxdmcp              1.1.3  h7f98852_0                    conda-forge     Cached
  + pthread-stubs                0.4  h36c2ea0_1001                 conda-forge     Cached
  + libunistring              0.9.10  h7f98852_0                    conda-forge     Cached
  + gettext                   0.21.1  h27087fc_0                    conda-forge     Cached
  + pkg-config                0.29.2  h36c2ea0_1008                 conda-forge     Cached
  + voro                       0.4.6  h00ab1b0_0                    conda-forge     Cached
  + libbrotlicommon            1.1.0  hd590300_1                    conda-forge     Cached
  + xorg-libxau               1.0.11  hd590300_0                    conda-forge     Cached
  + libdeflate                  1.19  hd590300_0                    conda-forge     Cached
  + lerc                       4.0.0  h27087fc_0                    conda-forge     Cached
  + libwebp-base               1.3.2  hd590300_0                    conda-forge     Cached
  + lz4-c                      1.9.4  hcb278e6_0                    conda-forge     Cached
  + icu                         73.2  h59595ed_0                    conda-forge     Cached
  + libiconv                    1.17  h166bdaf_0                    conda-forge     Cached
  + snappy                    1.1.10  h9fff704_0                    conda-forge     Cached
  + c-ares                    1.23.0  hd590300_0                    conda-forge      154kB
  + libev                       4.33  h516909a_1                    conda-forge     Cached
  + libnsl                     2.0.1  hd590300_0                    conda-forge     Cached
  + libffi                     3.4.2  h7f98852_5                    conda-forge     Cached
  + bzip2                      1.0.8  hd590300_5                    conda-forge     Cached
  + ncurses                      6.4  h59595ed_2                    conda-forge     Cached
  + libaec                     1.1.2  h59595ed_1                    conda-forge     Cached
  + libjpeg-turbo              3.0.0  hd590300_1                    conda-forge     Cached
  + libuuid                   2.38.1  h0b41bf4_0                    conda-forge     Cached
  + libexpat                   2.5.0  hcb278e6_1                    conda-forge     Cached
  + xz                         5.2.6  h166bdaf_0                    conda-forge     Cached
  + libgfortran5              13.2.0  ha4646dd_3                    conda-forge     Cached
  + openssl                    3.2.0  hd590300_1                    conda-forge     Cached
  + libzlib                   1.2.13  hd590300_5                    conda-forge     Cached
  + keyutils                   1.6.1  h166bdaf_0                    conda-forge     Cached
  + libidn2                    2.3.4  h166bdaf_0                    conda-forge     Cached
  + libbrotlienc               1.1.0  hd590300_1                    conda-forge     Cached
  + libbrotlidec               1.1.0  hd590300_1                    conda-forge     Cached
  + libxcb                      1.15  h0b41bf4_0                    conda-forge     Cached
  + libedit             3.1.20191231  he28a2e2_2                    conda-forge     Cached
  + readline                     8.2  h8228510_1                    conda-forge     Cached
  + libgfortran-ng            13.2.0  h69a702a_3                    conda-forge     Cached
  + libzip                    1.10.1  h2629f0a_3                    conda-forge     Cached
  + libxml2                   2.11.6  h232c23b_0                    conda-forge     Cached
  + tk                        8.6.13  noxft_h4845f30_101            conda-forge     Cached
  + libsqlite                 3.44.2  h2797004_0                    conda-forge     Cached
  + zlib                      1.2.13  hd590300_5                    conda-forge     Cached
  + hdf4                      4.2.15  h2a13503_7                    conda-forge     Cached
  + libnghttp2                1.58.0  h47da74e_0                    conda-forge     Cached
  + zstd                       1.5.5  hfc55251_0                    conda-forge     Cached
  + libssh2                   1.11.0  h0841786_0                    conda-forge     Cached
  + libpng                    1.6.39  h753d276_0                    conda-forge     Cached
  + brotli-bin                 1.1.0  hd590300_1                    conda-forge     Cached
  + krb5                      1.21.2  h659d440_0                    conda-forge     Cached
  + libopenblas               0.3.25  pthreads_h413a1c8_0           conda-forge     Cached
  + fftw                      3.3.10  nompi_hc118613_108            conda-forge     Cached
  + wget                      1.20.3  ha35d2d1_1                    conda-forge     Cached
  + openmpi                    4.1.6  hc5af2df_101                  conda-forge     Cached
  + libtiff                    4.6.0  ha9c0a0a_2                    conda-forge     Cached
  + blosc                     1.21.5  h0f2a231_0                    conda-forge     Cached
  + freetype                  2.12.1  h267a509_2                    conda-forge     Cached
  + brotli                     1.1.0  hd590300_1                    conda-forge     Cached
  + libcurl                    8.4.0  hca28451_0                    conda-forge     Cached
  + libblas                    3.9.0  20_linux64_openblas           conda-forge     Cached
  + kim-api                    2.3.0  h94b5c5c_0                    conda-forge     Cached
  + lcms2                       2.16  hb7c19ff_0                    conda-forge      245kB
  + openjpeg                   2.5.0  h488ebb8_3                    conda-forge     Cached
  + hdf5                      1.14.2  nompi_h4f84152_100            conda-forge     Cached
  + libcblas                   3.9.0  20_linux64_openblas           conda-forge     Cached
  + liblapack                  3.9.0  20_linux64_openblas           conda-forge     Cached
  + libnetcdf                  4.9.2  nompi_h80fb2b6_112            conda-forge     Cached
  + gsl                          2.7  he838d99_0                    conda-forge     Cached
  + mlip                         2.0  h7b20f27_0                    conda-forge     Cached
  + tzdata                     2023c  h71feb2d_0                    conda-forge     Cached
  + python                    3.11.6  hab00c5b_0_cpython            conda-forge     Cached
  + wheel                     0.42.0  pyhd8ed1ab_0                  conda-forge     Cached
  + setuptools                68.2.2  pyhd8ed1ab_0                  conda-forge     Cached
  + pip                       23.3.1  pyhd8ed1ab_0                  conda-forge     Cached
  + zipp                      3.17.0  pyhd8ed1ab_0                  conda-forge     Cached
  + six                       1.16.0  pyh6c4a22f_0                  conda-forge     Cached
  + blinker                    1.7.0  pyhd8ed1ab_0                  conda-forge     Cached
  + click                      8.1.7  unix_pyh707e725_0             conda-forge     Cached
  + munkres                    1.1.4  pyh9f0ad1d_0                  conda-forge     Cached
  + pyparsing                  3.1.1  pyhd8ed1ab_0                  conda-forge     Cached
  + packaging                   23.2  pyhd8ed1ab_0                  conda-forge     Cached
  + cycler                    0.12.1  pyhd8ed1ab_0                  conda-forge     Cached
  + certifi               2023.11.17  pyhd8ed1ab_0                  conda-forge     Cached
  + itsdangerous               2.1.2  pyhd8ed1ab_0                  conda-forge     Cached
  + importlib-metadata         7.0.0  pyha770c72_0                  conda-forge       26kB
  + python-dateutil            2.8.2  pyhd8ed1ab_0                  conda-forge     Cached
  + markupsafe                 2.1.3  py311h459d7ec_1               conda-forge     Cached
  + pillow                    10.1.0  py311ha6c5da5_0               conda-forge     Cached
  + kiwisolver                 1.4.5  py311h9547e67_1               conda-forge     Cached
  + n2p2                       2.2.0  py311h84d189c_4               conda-forge     Cached
  + numpy                     1.26.2  py311h64a7726_0               conda-forge     Cached
  + fonttools                 4.46.0  py311h459d7ec_0               conda-forge        3MB
  + contourpy                  1.2.0  py311h9547e67_0               conda-forge     Cached
  + scipy                     1.11.4  py311h64a7726_0               conda-forge     Cached
  + f90wrap                   0.2.13  py311hbc92942_2               conda-forge     Cached
  + matplotlib-base            3.8.2  py311h54ef318_0               conda-forge     Cached
  + werkzeug                   3.0.1  pyhd8ed1ab_0                  conda-forge     Cached
  + jinja2                     3.1.2  pyhd8ed1ab_1                  conda-forge     Cached
  + flask                      3.0.0  pyhd8ed1ab_0                  conda-forge     Cached
  + ase                       3.22.1  pyhd8ed1ab_1                  conda-forge     Cached
  + quippy                    0.9.12  py311hb1b10de_1               conda-forge     Cached
  + lammps                2023.08.02  cpu_py311_hf0e8f25_openmpi_7  conda-forge     Cached

  Summary:

  Install: 110 packages

  Total download: 3MB

────────────────────────────────────────────────────────────────────────────────────────────
```

### PR DESCRIPTION
**Pull request by njzjz**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #171

### CODE REVIEW

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
mlip and n2p2 do not have `nompi` variant

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Pull request merged**
