### PR TITLE
Try to enable kokkos based CUDA builds

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Somehow the compiler version and the cuda version are decoupled, while they should be always matching.

**Comment by xhochy** [comment]
No, this looks actually just about right. Different CUDA versions need different compiler versions.

**Comment by jan-janssen** [comment]
> No, this looks actually just about right. Different CUDA versions need different compiler versions.

@xhochy I agree but currently it is building all CUDA versions with all compiler versions which is not the correct way, as far as I understand. It should be one compiler version per CUDA version.

**Comment by njzjz** [comment]
I check the files and think it is right. The Linux matrix includes Python version (6), CUDA version (5), and MPI (2), so there are 6*5*2=60 in total.

**Comment by jan-janssen** [comment]
I looked again at the tests that failed:
```
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpiopenmpinumpy1.23python3.11.____cpython failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpiopenmpinumpy1.21python3.9.____cpython failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpiopenmpinumpy1.21python3.9.____73_pypy failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpiopenmpinumpy1.21python3.8.____cpython failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpiopenmpinumpy1.21python3.8.____73_pypy failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpiopenmpinumpy1.21python3.10.____cpython failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpimpichnumpy1.23python3.11.____cpython failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpimpichnumpy1.21python3.9.____cpython failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpimpichnumpy1.21python3.9.____73_pypy failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpimpichnumpy1.21python3.8.____cpython failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpimpichnumpy1.21python3.8.____73_pypy failed
linux linux_64_c_compiler_version7cuda_compilernvcccuda_compiler_version10.2cxx_compiler_version7fortran_compiler_version7mpimpichnumpy1.21python3.10.____cpython failed
```
these are all `cuda 10.2` tests, so it seems LAMMPS does not support this old cuda version.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
