### PR TITLE
add libpnetcdf to requirements

### PR DESCRIPTION
**Pull request by njzjz**
This prevents https://github.com/conda-forge/lammps-feedstock/issues/199 in the coming versions. Old versions should be patched in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock.

### CODE REVIEW

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by njzjz** [comment]
Oh I notice the disscusion in #198. I will revert the changes for `stdlib` and leave the changes in other PRs.

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by jan-janssen** [comment]
@njzjz  thanks a lot for taking care of this.

**Pull request merged**
