### PR TITLE
Update to 2021.09.29 update 3

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by akohlmey** [comment]
FYI, a new stable release of LAMMPS is coming very soon (perhaps next week).

**Comment by jan-janssen** [comment]
@akohlmey thanks for the heads up, the issue with the latest patch releases is that

**Comment by akohlmey** [comment]
> @akohlmey thanks for the heads up, the issue with the latest patch releases is that you replaced `reverse_comm_fix` with `forward_comm` and `forward_comm_fix` with `forward_comm`[1]

That is a bit unfortunate, but changes like this will continue to happen for a while while we try to streamline and refactor some of the internals to a more modern C++ programming styles with simpler, cleaner, and and better abstracted interfaces. The current interface still shows many signs of its origin as Fortran 90 modules (and before that Fortran 77 COMMON blocks).

On the other hand, I should also point out the improved support for building extensions/packages as a plugin and having them loaded transparently at runtime. This should hopefully help with packaging by reducing the dependencies of the base package.
One obvious example would be the VTK package that requires many dependencies due to VTK itself.
It will also allow to include packages with incompatible licenses, e.g. the ML-PACE package which uses an external library that is available only under GPLv3 while LAMMPS is GPLv2 (not a problem if you are building from source yourself). For that to work, you can consider the core LAMMPS headers as LGPL licensed (we plan to make this official once we have finished the refactoring of the internal interfaces and moved them to a separate folder and have split the exported from the private interfaces). At that point the intention is to have those represent a stable API with limited changes (and backward compatible ones if possible) to improve the situation for developers of external packages, but that is still a long way from completion.

**Comment by jan-janssen** [comment]
@akohlmey While I agree that users should compile their own LAMMPS version to achieve the optimal performance, I see the advantage in the conda version that new users can test it in a workshop or lecture setting. For example in workshops like http://potentials.rub.de an existing set of structures from DFT calculation are evaluated with LAMMPS to compute the SNAP or ACE descriptors, these descriptors are then fitted to create a interatomic potential and finally the interatomic potential is used inside LAMMPS to calculate properties which are not accessible with DFT. So having an executable which can be installed from a commonly used package manager allows the participants to focus on the scientific content of the workshop while still executing the whole workflow on their own computer without any dependence on the workshop infrastructure. Seeing that over 600 000 people downloaded the conda package is I guess an indication that there is a need for a binary distribution.

**Comment by akohlmey** [comment]
> I guess an indication that there is a need for a binary distribution

There is no question about that. I build binary packages for Windows for the same reasons (It was started for a workshop and then kept going because the demand was there. Once there was a working build and packaging script, it was only a moderate effort to keep it going).

But that is not how LAMMPS was initially designed and what some of the core LAMMPS developers are familiar with.

But over the years we have introduced multiple changes to support packaging and in response to issues reported from maintainers of LAMMPS binary packages. The fact that we post updates to the stable branch which should remain ABI compatible is the latest step (next to the already mentioned plugin interface).

**Pull request merged**
